In [22]:
# Q1
# a
import os
import json
try:
    with open ("DublinAirport090220.json") as f:
        line = json.load(f)
        print(line)
except Exception as e:
    raise e

[{'name': 'Dublin Airport', 'temperature': '11', 'symbol': '40n', 'weatherDescription': 'Light rain showers', 'text': '"Recent Rain"', 'windSpeed': '41', 'windGust': '70', 'cardinalWindDirection': 'SW', 'windDirection': 225, 'humidity': ' 85 ', 'rainfall': ' 0.1 ', 'pressure': '986', 'dayName': 'Sunday', 'date': '09-02-2020', 'reportTime': '00:00'}, {'name': 'Dublin Airport', 'temperature': '11', 'symbol': '46n', 'weatherDescription': 'Light rain ', 'text': '"Light rain "', 'windSpeed': '37', 'windGust': '72', 'cardinalWindDirection': 'SW', 'windDirection': 225, 'humidity': ' 89 ', 'rainfall': ' 0.01 ', 'pressure': '986', 'dayName': 'Sunday', 'date': '09-02-2020', 'reportTime': '01:00'}, {'name': 'Dublin Airport', 'temperature': '11', 'symbol': '46n', 'weatherDescription': 'Light rain ', 'text': '"Light rain "', 'windSpeed': '30', 'windGust': '65', 'cardinalWindDirection': 'SW', 'windDirection': 225, 'humidity': ' 92 ', 'rainfall': ' 0.8 ', 'pressure': '987', 'dayName': 'Sunday', 'date

In [27]:
# Q1
# b
print("Temperature")
for i in range(len(line)):
    print(line[i]["temperature"])

print("--------\nweatherDescription")
for i in range(len(line)):
    print(line[i]["weatherDescription"])

print("--------\nreportTime")
for i in range(len(line)):
    print(line[i]["reportTime"])

Temperature
11
11
11
11
11
11
11
11
10
9
10
11
10
11
7
8
8
7
7
7
6
6
6
5
--------
weatherDescription
Light rain showers
Light rain 
Light rain 
Light rain 
Light rain 
Light rain 
Light rain 
Light rain 
Rain
Light rain 
Rain showers
Rain showers
Light rain showers
Fair
Rain showers
Light rain showers
Light rain showers
Rain showers
Light rain showers
Light rain showers
Rain showers
Light rain showers
Rain showers
Rain showers
--------
reportTime
00:00
01:00
02:00
03:00
04:00
05:00
06:00
07:00
08:00
09:00
10:00
11:00
12:00
13:00
14:00
15:00
16:00
17:00
18:00
19:00
20:00
21:00
22:00
23:00


In [24]:
import xml.etree.ElementTree as ET
import csv

tree = ET.parse("DublinAirport090220.xml")
root = tree.getroot()

In [7]:
# Q2
# a
import numpy as np
b = np.arange(0,400,2)
print(b.shape)
print(b)
print(type(b))

(200,)
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398]
<class 'numpy.ndarray'>


In [6]:
# Q2
# b
Reshape_b=b.reshape(50,4)
print(Reshape_b.shape)
print(Reshape_b)
print(type(Reshape_b))

(50, 4)
[[  0   2   4   6]
 [  8  10  12  14]
 [ 16  18  20  22]
 [ 24  26  28  30]
 [ 32  34  36  38]
 [ 40  42  44  46]
 [ 48  50  52  54]
 [ 56  58  60  62]
 [ 64  66  68  70]
 [ 72  74  76  78]
 [ 80  82  84  86]
 [ 88  90  92  94]
 [ 96  98 100 102]
 [104 106 108 110]
 [112 114 116 118]
 [120 122 124 126]
 [128 130 132 134]
 [136 138 140 142]
 [144 146 148 150]
 [152 154 156 158]
 [160 162 164 166]
 [168 170 172 174]
 [176 178 180 182]
 [184 186 188 190]
 [192 194 196 198]
 [200 202 204 206]
 [208 210 212 214]
 [216 218 220 222]
 [224 226 228 230]
 [232 234 236 238]
 [240 242 244 246]
 [248 250 252 254]
 [256 258 260 262]
 [264 266 268 270]
 [272 274 276 278]
 [280 282 284 286]
 [288 290 292 294]
 [296 298 300 302]
 [304 306 308 310]
 [312 314 316 318]
 [320 322 324 326]
 [328 330 332 334]
 [336 338 340 342]
 [344 346 348 350]
 [352 354 356 358]
 [360 362 364 366]
 [368 370 372 374]
 [376 378 380 382]
 [384 386 388 390]
 [392 394 396 398]]
<class 'numpy.ndarray'>


In [10]:
# 2
# c # i
Reshape_b[:,3]

array([  6,  14,  22,  30,  38,  46,  54,  62,  70,  78,  86,  94, 102,
       110, 118, 126, 134, 142, 150, 158, 166, 174, 182, 190, 198, 206,
       214, 222, 230, 238, 246, 254, 262, 270, 278, 286, 294, 302, 310,
       318, 326, 334, 342, 350, 358, 366, 374, 382, 390, 398])

In [11]:
# 2
# c # ii
Reshape_b[::2]

array([[  0,   2,   4,   6],
       [ 16,  18,  20,  22],
       [ 32,  34,  36,  38],
       [ 48,  50,  52,  54],
       [ 64,  66,  68,  70],
       [ 80,  82,  84,  86],
       [ 96,  98, 100, 102],
       [112, 114, 116, 118],
       [128, 130, 132, 134],
       [144, 146, 148, 150],
       [160, 162, 164, 166],
       [176, 178, 180, 182],
       [192, 194, 196, 198],
       [208, 210, 212, 214],
       [224, 226, 228, 230],
       [240, 242, 244, 246],
       [256, 258, 260, 262],
       [272, 274, 276, 278],
       [288, 290, 292, 294],
       [304, 306, 308, 310],
       [320, 322, 324, 326],
       [336, 338, 340, 342],
       [352, 354, 356, 358],
       [368, 370, 372, 374],
       [384, 386, 388, 390]])

In [12]:
Reshape_b[:,1] + Reshape_b[:,2]

array([  6,  22,  38,  54,  70,  86, 102, 118, 134, 150, 166, 182, 198,
       214, 230, 246, 262, 278, 294, 310, 326, 342, 358, 374, 390, 406,
       422, 438, 454, 470, 486, 502, 518, 534, 550, 566, 582, 598, 614,
       630, 646, 662, 678, 694, 710, 726, 742, 758, 774, 790])

In [16]:
# Q3
str='''Tweet Twoo Twitter Town
Have you seen a Toon too?
At noon in the townhall
The yellow sun soon shone.'''

In [17]:
# Q3
# a
import re
Newstr=re.sub(r"([a-z])\1","{\\1\\1}",str)
print(Newstr)

Tw{ee}t Tw{oo} Twi{tt}er Town
Have you s{ee}n a T{oo}n t{oo}?
At n{oo}n in the townha{ll}
The ye{ll}ow sun s{oo}n shone.


In [18]:
# Q3
# b
import re
Newstr=re.sub(r"\?","{?}",str)
print(Newstr)

Tweet Twoo Twitter Town
Have you seen a Toon too{?}
At noon in the townhall
The yellow sun soon shone.
